<?php
	session_start();
	if(isset($_SESSION['admin']))
	{
		unset($_SESSION['admin']);
		session_destroy();
		header('location:index.php');
	}
	else
	{
		header('location:index.php');
	}
?>